#You can change the name of the device here. 
#If you want to use multiple HassBeams, they need to have unique names.
device_name: hassbeam
#devicename string that is used for home assistant events. Its recommended to keep it the same as device_name
device_name_str: '"hassbeam"'


#enter your Wi-Fi SSID and password here
#(this should be the same network to which your home assistant instance is connected)
wifi_ssid: "YourWifiSSID"
wifi_password: "YourWifiPassword"


#enter a Fallback SSID and password
#(in the event that the esp32 cannot connect to the specified Wifi, it will create a fallback hotspot with this SSID and Password)
fallback_ssid: "FallbackSSID"
fallback_password: "FallbackPassword"