#enter your Wi-Fi SSID and password here
#(this should be the same network to which your homeassistant instance is connected)
wifi_ssid: "YourWifiSSID"
wifi_password: "YourWifiPassword"

#enter a Fallback SSID and password
#(in the event that the esp32 cannot connect to the specified Wifi, it will create a fallback Hotspot with this SSID and Password)
fallback_ssid: "FallbackSSID"
fallback_password: "FallbackPassword"
